name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff .
    - name: Type check with mypy
      run: |
        pip install mypy
        mypy . --exclude venv --ignore-missing-imports
    - name: Audit dependencies with pip-audit
      run: |
        pip install pip-audit
        pip-audit
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
